
package cxf_generated;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.1
 * 2020-11-17T11:01:34.410+03:00
 * Generated source version: 3.4.1
 *
 */
public final class NumberConversionSoapType_NumberConversionSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.dataaccess.com/webservicesserver/", "NumberConversion");

    private NumberConversionSoapType_NumberConversionSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = NumberConversion.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        NumberConversion ss = new NumberConversion(wsdlURL, SERVICE_NAME);
        NumberConversionSoapType port = ss.getNumberConversionSoap();

        {
        System.out.println("Invoking numberToWords...");
        java.math.BigInteger _numberToWords_ubiNum = new java.math.BigInteger("155");
        java.lang.String _numberToWords__return = port.numberToWords(_numberToWords_ubiNum);
        System.out.println("numberToWords.result=" + _numberToWords__return);


        }
        {
        System.out.println("Invoking numberToDollars...");
        java.math.BigDecimal _numberToDollars_dNum = new java.math.BigDecimal("154");
        java.lang.String _numberToDollars__return = port.numberToDollars(_numberToDollars_dNum);
        System.out.println("numberToDollars.result=" + _numberToDollars__return);


        }

        System.exit(0);
    }

}
